import type { Metadata } from 'next';
import { Outfit } from 'next/font/google';
import ReduxProvider from '@/redux/provider';
import './globals.css';

const outfit = Outfit({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
